# print(type("hello world"))
# print(type(123))
# print(type(12.3))
# print(type(False))
# print(type(()))
# print(type([]))
# print(type({}))
# a=float(input("请输入：",))
# b=float(input("请输入：",))
# print("input获取的内容",a+b)
# a = 'ndljsahdfhufywqyeihdfbaudfgaskmfhuyehpiehf'
# print(len(a))
a = input('请输入第一段:')
b = input('请输入第二段:')
print ('input获取的值',len(a+b))